apiVersion: apps/v1
kind: Deployment
metadata:
  name: modernapp
spec:
  template:
    spec:
      containers:
      - name: modernapp
        env:
          - name: PORT
            value: "8080"
          - name: TARGET
            value: "Staging Env - K8s Cluster"              